# Generated by Django 4.2 on 2023-05-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Пользователь'), ('admin', 'Админ'), ('moderator', 'Модератор')], default='member', max_length=9),
        ),
    ]
